org: draktate
app: trendmicro
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: book4me-api
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  timeout: 15
  runtime: nodejs12.x
  region: us-east-1

plugins: 
  - serverless-offline

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+} 
      - http: ANY / 
    environment:
      MONGO: mongodb+srv://draktate:tfaug123@cluster0.cxodglc.mongodb.net/dnyDB
      MONGO2:  mongodb+srv://draktate:Tfaug@2808@cluster0.cxodglc.mongodb.net/Cluster0?retryWrites=true&w=majority
      MONGO1: mongodb://draktate:tfaug123@localhost:27017/dnyDB
      JWT: ABCDEFGHIJKLMNOPQRSTUVWXYZ
      PORT: 7200
      ORIGINs: http://localhost:3000,https://master.d1zn1rfcz5wa41.amplifyapp.com